config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users
  resources :articles
=begin
verbos del https, rutas y metodos que manda a llamar en el controlador
verbo 		ruta 			metodo
get		"/articles" 		index
post 	"/articles"			create
delete 	"/articles/:id"			delete
get		"/articles/:id" 	show
get		"/articles/new" 	new
get		"articles/:id/edit" edit
patch	"/articles/:id" 	update
put 	"/article/:id" 		update

=end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
belongs_to :user
validates :title,presence: true, uniqueness: true
validates :body, presence: true, length: {minimum: 20}
#message: "prueba de msj personalizados", notice: "Pruebadesdecontrolador"
#validates :username, format: {with: /regex/} -> valida al usuario

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#Get /articles
	def index
		#select * from tabla
		@articles = Article.all
	end
	#get /articles/:id
	def show
		#select * from tabla where 
		@article = Article.find(params[:id])
		#Article.where("body LIKE ?",)
		#Article.where("body LIKE ?",)
		#Article.where("id = ?", params[:id]) ->evita el sql injection
		#Article.where.not("id = ?", params[:id]) -> diferente del que se selecciono
		#Article.where("id = #{params[:id]}") <- sql injection, es vulnerable

	end	
	#get /articles/new
	def new
		@article = Article.new	
	end
	#post /articles
	def create
	#insert  
		@article = current_user.articles.new(article_params)
		#@article = Article.new( title: params[:article][:title],body: params[:article][:body])
		 #@article.invalid?
		if @article.save  #guardar en la db
		redirect_to @article
			else
				render :new
			end
	end
	
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path	
	end

	def edit
		@article =Article.find(params[:id])
	end

	#PUT /articles/:ID
	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

#todo lo que esta debajo de private herdean la privbacidad, strong params
	private 
	def article_params
		params.require(:article).permit(:title,:body)
	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Crear" %>

<h1> <%= name%> Articulo </h1>
<%= form_for(@article) do |f|%>
			<% @article.errors.full_messages.each do |message| %>
				<div class="be-red white top-sapce">
					*<%= message %>
				</div>
				<%end%>
		<div class="field">
			<%= f.text_field :title, placeholder: "Titulo", class:"form_control" %>
		</div>
		<div class="field">
			<%= f.text_area :body, placeholder: "Text area", style:"height:250px;", class:"form_control" %>
		</div>
		<div class="field">
			<%= f.submit  "puchale", class:"btn be-red white" %>
		</div>
		<div class="field"></div>
	<% end %>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
	
	<%= render "form", name: "Editar" %>

</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1>  <%= link_to article.title, article %></h1>
	<div> <%= article.body %> ** <%= link_to "ELIMINAR",article, method: :delete, class:"red" %> </div>
<% end %>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
	<h1>CREAR</h1>
	<%= form_for(@article) do |f|%>
			<% @article.errors.full_messages.each do |message| %>
				<div class="be-red white top-sapce">
					*<%= message %>
				</div>
				<%end%>
		<div class="field">
			<%= f.text_field :title, placeholder: "Titulo", class:"form_control" %>
		</div>
		<div class="field">
			<%= f.text_area :body, placeholder: "Text area", style:"height:250px;", class:"form_control" %>
		</div>
		<div class="field">
			<%= f.submit  "puchale", class:"btn be-red white" %>
		</div>
		<div class="field"></div>
	<% end %>

</div>

app/views/articles/show.html.erb
	<h1>  <%= @article.title %></h1>
	<div> <%= @article.body %></div>
	<div> <%= link_to  "editar", edit_article_path(@article)%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
   <%= csrf_meta_tags %>
   <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  	  
		 <%= render "/partial/navigation" %>
		 
	<p class="notice"><%= notice %></p>
 	<p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/partial/_navigation.html.erb
 <header>
 <nav class="be-red white large_padding">
			  <ul class="no-list row center-xs middle-xs">
			  	<li class="col-md"> 
			  		<h1 class="no-margin" id="logo ">logo</h1> 
			  	</li>
			  	<li class="col-md"> 
			  		<%= link_to "Inicio", root_path %>
			  	</li>		  			  		
			  	<li class="col-md"> Texto1 </li>
			  	<li class="col-md"> Texto4 </li>
			  	<li class="col-md"> Text45 </li>
			  	<% if user_signed_in? %>
			  	<li class="col-md"> 
			  		<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>			  		
			  	</li>
			  	<%else%>
				  	<li class="col-md"> 
				  		<%= link_to "Iniciar sesión", new_user_session_path %>			  		
				  	</li>
				  	<li class="col-md"> 
				  		<%= link_to "Crear cuenta", new_user_registration_path %>			  		
				  	</li>
			  	<%end%>
			  </ul>	  	
  </nav>
</header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
<h1>Welcome <%= current_user.email %></h1>
<% end%>